name: Spring Boot CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name:  Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ️ Run tests with Maven
        run: mvn clean test

  build-and-deploy:
    name:  Build and Deploy
    runs-on: ubuntu-latest
    needs: test   # 👉 Only runs if 'test' job passes

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name:  Build JAR with Maven
        run: mvn clean package

      - name:  Show JAR file (demo)
        run: ls -l target/*.jar

      - name:  Simulate Deployment
        run: echo "Deploying application to test server..."
